import assert from "node:assert/strict";
import fs from "node:fs/promises";


const path = new URL("../js/jindouyun_multimodal_llm.js", import.meta.url);
const source = await fs.readFile(path, "utf8");

assert.match(source, /const NODE_TYPE = "JindouyunMultimodalLLM"/);
assert.match(source, /OpenAI/);
assert.match(source, /DeepSeek/);
assert.match(source, /阿里云百炼/);
assert.match(source, /豆包（火山方舟）/);
assert.match(source, /智谱AI/);
assert.match(source, /Kimi/);
assert.match(source, /小米MiMo/);
assert.match(source, /自定义 OpenAI 兼容/);
assert.match(source, /keyInput\.type = "password"/);
assert.match(source, /const modelSelect = document\.createElement\("select"\)/);
assert.match(source, /modelSelect\.replaceChildren\(\)/);
assert.match(source, /modelSelect\.append\(option\)/);
assert.match(source, /modelSelect\.addEventListener\("change"/);
assert.match(source, /manualModeButton\.addEventListener\("click"/);
assert.doesNotMatch(source, /createElement\("datalist"\)/);
assert.match(source, /findWidget\(node, "系统提示词"\)/);
assert.match(source, /findWidget\(node, "对话内容"\)/);
assert.match(source, /findWidget\(node, "温度"\)/);
assert.match(source, /findWidget\(node, "最大输出Token"\)/);
assert.match(source, /findWidget\(node, "超时秒数"\)/);
assert.match(source, /findWidget\(node, "锁定回复"\)/);
assert.match(source, /domWidget\.serialize = false/);
assert.doesNotMatch(source, /node\.widgets\.unshift/);
assert.match(source, /normalizedNumber\(temperatureWidget\.value, 0\.7, 0, 2\)/);
assert.match(source, /normalizedNumber\(maxTokensWidget\.value, 2048, 1, 131072, true\)/);
assert.match(source, /normalizedNumber\(timeoutWidget\.value, 120, 5, 7200, true\)/);
assert.match(source, /maxTokens <= 4 && timeout >= 256/);
assert.match(source, /已自动修复旧工作流参数/);
assert.match(source, /jindouyun\.multimodal\.apiKeys/);
assert.match(source, /jindouyun\.multimodal\.promptPresets/);
assert.match(source, /window\.localStorage\?\.setItem/);
assert.match(source, /storedProviderValue\(API_KEYS_STORAGE_KEY/);
assert.match(source, /rememberProviderValue\(API_KEYS_STORAGE_KEY/);
assert.match(source, /function isForeignProviderPreset\(provider, value\)/);
assert.match(source, /function resolvedProviderBaseUrl\(provider, \.\.\.candidates\)/);
assert.match(source, /已修复供应商地址/);
assert.match(source, /种子模式/);
assert.match(source, /固定种子：复用当前回复/);
assert.match(source, /随机种子：每次生成新回复/);
assert.match(source, /提示词预设/);
assert.match(source, /自定义预设名称/);
assert.match(source, /saveCurrentPromptPreset/);
assert.match(source, /applySelectedPromptPreset/);
assert.match(source, /deletePromptPreset/);
assert.match(source, /width: "calc\(100% - 24px\)"/);
assert.match(source, /const MIN_PANEL_HEIGHT = 550/);
assert.match(source, /const MIN_NODE_HEIGHT = 790/);
assert.match(source, /function syncPanelSize\(node, wrapper, requestedWidth\)/);
assert.match(source, /Number\(node\.size\?\.\[1\] \|\| MIN_NODE_HEIGHT\) - PANEL_VERTICAL_OFFSET/);
assert.match(source, /flex: "1 1 58px"/);
assert.match(source, /flex: "1 1 0"/);
assert.match(source, /const \[panelWidth\] = syncPanelSize\(node, wrapper, width\)/);
assert.match(source, /return \[panelWidth, MIN_PANEL_HEIGHT\]/);
assert.match(source, /node\.onResize = function\(\)/);
assert.doesNotMatch(source, /getMaxHeight: \(\) =>/);
assert.match(source, /api\.fetchApi\("\/jindouyun_design\/llm\/models"/);
assert.match(source, /获取模型/);
assert.match(source, /makeButton\("获取 Key"/);
assert.match(source, /window\.open\(preset\.keyUrl/);
assert.match(source, /node\.addDOMWidget\("模型服务设置"/);
assert.match(source, /beforeRegisterNodeDef\(nodeType, nodeData\)/);
assert.match(source, /供应商/);
assert.match(source, /API密钥/);
assert.match(source, /Base URL/);
assert.match(source, /模型名称/);

console.log("multimodal LLM UI source tests passed");
